services:
  auth-db:
    image: postgres:16-alpine
    container_name: postgres_auth
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - microservices-net


  order-db:
    image: postgres:16-alpine
    container_name: postgres_order
    environment:
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  user_db_data:
  order_db_data:
    driver: local